swagger: '2.0'
info:
  title: "memecoins Merchant api"
  description: 'memecoins Merchant api 文档'
  termsOfService: ''
  contact:
    email: sales@techrare.com
  version: 1.0.0

host: 'localhost:8082'
basePath: /memecoinsapi/public/api
$ref#common: "./common.yaml"