swagger: '2.0'
info:
  version: 0.0.1
  title: memecoins網紅
  description: memecoins網紅API
  termsOfService: terms
host: 'office.techrare.com:5681'
basePath: /memecoinsapi/public/api/generalize
schemes:
  - http
consumes:
  - application/x-www-form-urlencoded
paths:
  /auth/login:
    post:
      summary: 用戶登錄
      description: 用戶登錄
      parameters:
        - name: phone
          in: formData
          description: 手機號碼
          required: true
          type: string
        - name: code
          in: formData
          description: 短信驗證碼
          required: true
          type: string
      tags:
        - User
      responses:
        '200':
          description: 用户信息和token
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /auth/logout:
    get:
      summary: 用戶注銷
      description: 用戶注銷
      tags:
        - User
      responses:
        '200':
          description: 返回成功
        default:
          description: token無效
  /auth/sms:
    post:
      summary: 短信驗證碼
      description: 短信驗證碼
      parameters:
        - name: phone
          in: formData
          description: 手機號碼
          required: true
          type: string
      tags:
        - User
      responses:
        '200':
          description: 返回短信發送成功
        default:
          description: 返回用戶不存在或號碼輸入錯誤
  /user/info:
    get:
      summary: 用戶個人信息
      description: 用戶個人信息
      tags:
        - User
      responses:
        '200':
          description: 返回用戶數據
      security:
        - Bearer: []
  /user/alterinfo:
    post:
      summary: 修改個人信息
      description: 修改個人信息
      tags:
        - User
      parameters:
        - name: nickname
          in: formData
          required: false
          type: string
        - name: gender
          in: formData
          required: false
          type: number
        - name: avatar
          in: formData
          required: false
          type: string
        - name: birthday
          in: formData
          required: false
          type: string
      responses:
        '200':
          description: 返回修改成功
        default:
          description: 返回錯誤信息
      security:
        - Bearer: []
  /bank/accountinfo:
    get:
      summary: 銀行卡信息
      description: 銀行卡信息
      tags:
        - Bank
      responses:
        '200':
          description: 返回銀行信息
      security:
        - Bearer: []
  /bank/alter:
    post:
      summary: 修改銀行卡信息
      description: 修改銀行卡信息
      tags:
        - Bank
      parameters:
        - name: bank_name
          in: formData
          required: false
          type: string
          description: 銀行名稱
        - name: receiver_name
          in: formData
          required: false
          type: string
          description: 收款人姓名
        - name: bank_account
          in: formData
          required: false
          type: string
          description: 收款人賬戶
        - name: bank_phone
          in: formData
          required: false
          type: string
          description: 收款人手機號碼
      responses:
        '200':
          description: 返回修改成功
        default:
          description: 返回錯誤信息
      security:
        - Bearer: []
  /ranking/invite:
    get:
      summary: 邀請排行榜
      description: 邀請排行榜
      tags:
        - Ranking
      parameters:
        - name: per_page
          description: 每頁數量-默認10
          type: integer
          in: query
        - name: page
          description: 頁數-默認1
          type: integer
          in: query
      responses:
        '200':
          description: 返回用戶數據
      security:
        - Bearer: []
  /ranking/money:
    get:
      summary: 邀請獲得金錢排行榜
      description: 邀請獲得金錢排行榜
      tags:
        - Ranking
      parameters:
        - name: per_page
          description: 每頁數量-默認10
          type: integer
          in: query
        - name: page
          description: 頁數-默認1
          type: integer
          in: query
      responses:
        '200':
          description: 返回用戶數據
      security:
        - Bearer: []
  /activity/list:
    get:
      summary: 獲取活動列表
      description: 獲取活動列表
      tags:
        - Activity
      parameters:
        - name: per_page
          in: query
          type: integer
          description: 每頁條數
        - name: page
          in: query
          type: integer
          description: 頁數
      responses:
        '200':
          description: 返回列表數據
        default:
          description: token無效
      security:
        - Bearer: []
  /activity/detail:
    get:
      summary: 獲取活動詳情
      description: 獲取活動詳情
      tags:
        - Activity
      parameters:
        - name: id
          in: query
          type: integer
          description: 活動id
      responses:
        '200':
          description: 返回列表詳情
        default:
          description: token無效
      security:
        - Bearer: []
  /withdrawl/history:
    get:
      summary: 提現歷史
      description: 體現歷史記錄
      tags:
        - Withdraw
      parameters:
        - name: per_page
          in: query
          type: integer
          description: 每頁條數
        - name: page
          in: query
          type: integer
          description: 頁數
      responses:
        '200':
          description: 返回數據
        default:
          description: token失效
      security:
        - Bearer: []
  /withdraw/apply:
    post:
      summary: 申請提現
      description: 申請提現
      tags:
        - Withdraw
      parameters:
        - name: amount
          in: formData
          type: number
          description: 申請數額
      responses:
        '200':
          description: 返回列表詳情
        default:
          description: token無效
      security:
        - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
tags:
  - name: User
    description: 用戶登錄、注銷、短信驗證碼、用戶信息及修改
  - name: Bank
    description: 銀行賬戶信息、銀行賬戶修改
  - name: Ranking
    description: 排行榜：金錢排行榜、邀請排行榜
  - name: Activity
    description: 活動列表、活動詳細內容
  - name: Withdraw
    description: 提現歷史記錄，提現申請
